
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Chris Redfield",
    "email": "chris.redfield@stars.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "9673a570-d3e7-4e88-a989-3b437e61c77b"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "a1",
    "account_id_to": "a2",
    "amount": 499
}